nest-next production build 문제 해결중
npx next dev 에서는 문제 발생하지 않음
npx next build 에서 문제 발생

Error: Could not find a production build in the '.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id

실 오류 메시지는 : Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.[missing argument]